modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Cutwell/MooshbloomMod/issues"

[[mods]]
modId="mooshbloommod"
version="1.0.0"
displayName="Mooshbloom Mod"
credits="Slexom"
authors="Cutwell"
logoFile="logo.png"
displayURL="https://github.com/Cutwell/MooshbloomMod"
description='''Bring mobs from Minecraft Earth to Minecraft Java Edition.'''
updateJSONURL="https://raw.githubusercontent.com/Cutwell/MooshbloomMod/master/update.json"

[[dependencies.mooshbloommod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"



